### ISSUE TITLE
Game failed due to error

### ISSUE THREAD

**Issue by nosound2** [glmcdona/LuxPythonEnvGym#62]
While training I am sporadically getting a "Game failed due to error" message. Does it mean that there is a bug that needs to be fixed, or can it happen naturally in game?

**Comment by glmcdona** [comment]
Yup, that means an unhandled exception occurred during the simulation of the game. This can be something like a bug in the game engine. View `match_errors.txt` in the working directory for the stack trace of the exception and please submit an issue with any you find. Make sure you are using the latest version of LuxPythonEnvGym too, since I've fixed a bunch of bugs too.
